Add missing casts to ChunkedDevice stored backend
This will fix, the following errors, when compiling for 32bit:

> core/src/stored/backends/chunked_device.cc: In member function ‘ssize_t storagedaemon::ChunkedDevice::ReadChunked(int, void*, size_t)’:
> core/src/include/bc_types.h:113:26: error: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Werror=sign-compare]
>   113 | #  define MIN(a, b) ((a) < (b) ? (a) : (b))
>       |                      ~~~~^~~~~
> core/src/stored/backends/chunked_device.cc:685:13: note: in expansion of macro ‘MIN’
>   685 |           = MIN((ssize_t)count, (current_chunk_->buflen - wanted_offset));
>       |             ^~~
> core/src/stored/backends/chunked_device.cc: In member function ‘ssize_t storagedaemon::ChunkedDevice::WriteChunked(int, const void*, size_t)’:
> core/src/stored/backends/chunked_device.cc:846:46: error: comparison of integer expressions of different signedness: ‘ssize_t’ {aka ‘int’} and ‘uint32_t’ {aka ‘unsigned int’} [-Werror=sign-compare]
>   846 |             if ((wanted_offset + bytes_left) > current_chunk_->buflen) {

There are already a lot of similar casts, so I suspect these ones were just
forgotten.